In [1]:
import numpy as np

In [2]:
# Task:1

In [7]:
x =  np.arange(1,13).reshape((6,2)) 

In [4]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [5]:
# Task2

In [11]:
x = np.arange(10,37,dtype=np.float64).reshape((3,3,3))

In [12]:
x

array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]],

       [[28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]]])

In [13]:
# Task:3

In [20]:
a = np.arange(1, 100*10+1).reshape((5,7))

ValueError: cannot reshape array of size 1000 into shape (5,7)

In [19]:
x = a[]

SyntaxError: invalid syntax (<ipython-input-19-f38d9be6c1b5>, line 1)

In [21]:
#Task:4

In [25]:
arr = np.arange(9).reshape(3,3)

In [26]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
#task5

In [36]:
z = np.zeros((4,5))

In [37]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
#task6

In [41]:
l=[0,0,0,0,0,10,0,0,20,0,0]

In [62]:
np.array(l)

array([ 0,  0,  0,  0,  0, 10,  0,  0, 20,  0,  0])

In [61]:
#task7

In [56]:
a=[0,0,0,0]

In [60]:
np.array(a, dtype=np.int64)

array([0, 0, 0, 0], dtype=int64)

In [91]:
z=np.array([[6,6,6,6,6],[6,6,6,6,6]])

In [92]:
z

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [93]:
#task9

In [100]:
np.arange(2,101,2,)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [101]:
#task10

In [103]:
arr = np.array([[3,3,3],[4,4,4],[5,5,5]])


In [104]:
brr = np.array([1,2,3])

In [105]:
arr - brr

array([[2, 1, 0],
       [3, 2, 1],
       [4, 3, 2]])

In [1]:
#task11

In [24]:
import numpy as np

In [25]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.where(arr=<3,-1,arr)

SyntaxError: invalid syntax (<ipython-input-26-7f26800c5075>, line 1)

In [28]:
salary=np.array([0,-1,100000,50000])

In [34]:
np.where(salary<=0,-1,25000,salary)

TypeError: where() takes from 1 to 3 positional arguments but 4 were given

In [35]:
#task13

In [36]:
arr = np.array([2, 6, 1, 9, 10, 3, 27])

In [39]:
arr[arr,5<10]

IndexError: index 9 is out of bounds for axis 0 with size 7